services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: task:latest
    container_name: task
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app:ro
    networks:
      - task_network
    restart: always
    user: node
    depends_on:
      - mysql
    command: ["npm", "run", "start:prod"]

  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - task_network
    restart: always

networks:
  task_network:
    driver: bridge

volumes:
  mysql_data:
